### ISSUE TITLE
Alternative case option

### ISSUE THREAD

**Issue by rhuba8324** [tristannottelman/Sulpog#1]
First, thanks for your incredible works!

I ran into a bit of a snag with the linked cases though. Pulling the USB-C cable seemed to yank the whole thing apart, and apparently some newer T-Displays have screens in a slightly different spot, making most cases a no-go.

So, I whipped up this new enclosure that should fix those problems, while addressing the two known issue you mention!
You can check it out here: https://www.printables.com/model/817468-ttgo-t-display-cases

Hope you can give it a try. Let me know if there's any issue.
Thanks again for the project

**Comment by tristannottelman** [comment]
@rhuba8324 Wow thank you for creating this awesome design. I'm definitely going to try it and I will let you know the result!

**Comment by tristannottelman** [comment]
@rhuba8324 Great design! I really appreciate the enhanced stability and the possibility to add a switch. I did have to slightly adjust the height to fit the battery mentioned in the readme. I've included a link to your case in the readme. Thanks once again.

**Comment by rhuba8324** [comment]
Glad my design worked for you!
